name: "Alexa Shopping List Scrapper"
description: "The project scrapes the Amazon Shopping List page and add the items to the Home Assistant Shopping List (todo list) every 3 minutes"
version: "1.0.5"
slug: "alexa_shopping_list_scrapper"
init: false
url: "https://github.com/thiagobruch/HA_Addons/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  Amazon_Login: "email@email.com"
  Amazon_Pass: "my_amazon_password"
  Amazon_Secret: "My OTP APP Secret"
  HA_Webhook_URL: "HOME_ASSISTANT_WEBHOOK_URL"
schema:
  Amazon_Login: str
  Amazon_Pass: password
  Amazon_Secret: password
  HA_Webhook_URL: str
