blueprint:
  name: Import Alexa shoppinglist
  description: Import Alexa shopping to your Home Assistant shopping list.
  domain: automation
  author: N1c093
  input:
    webhook_trigger:
      name: Webhook Trigger
      description: "Please create a webhook trigger. Other triggers are not supported!"
      selector:
        trigger: {}
    shopping_list:
      name: Shopping List
      description: Which shopping list should receive the entries from the Alexa shopping list?
      selector:
        entity:
          filter:
            domain: todo
mode: parallel
max: 100
variables:
  shopping_list: !input shopping_list
trigger: !input webhook_trigger

action:
  - data: {}
    response_variable: list
    entity_id: !input shopping_list
    action: todo.get_items
  - if:
      - condition: template
        value_template: >-
          {{trigger.json.name not in list[shopping_list]["items"] |
          map(attribute="summary") | list }}
    then:
      - entity_id: !input shopping_list
        data:
          item: "{{ trigger.json.name }}"
        action: todo.add_item
