name: "Beszel Agent for Home Assistant"
description: "The project creates a Beszel Agent to be used with Beszel from https://github.com/henrygd/beszel"
version: "0.0."
slug: "beszel-agent-for-ha"
init: false
url: "https://github.com/thiagobruch/HA_Addons/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  KEY: "email@email.com"
  PORT: "my_amazon_password"
schema:
  KEY: str
  PORT: int